version: '3.8'

services:
  web-app:
    build:
      context: .
      args:
        - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
        - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    container_name: spotimix
    restart: unless-stopped
    
    # --- MAPEAMENTO DE PORTA DINÂMICO ---
    ports:
      # Sintaxe: '${VARIAVEL:-VALOR_PADRAO}:PORTA_INTERNA'
      - '${PORTA_DO_HOST:-8080}:80'
    
    # --- GESTÃO DE VARIÁVEIS PRIVADAS ---
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - APP_ENV=production
    
    networks:
      - fvds-network

networks:
  fvds-network:
    external: true
