server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Essa configuração é vital para aplicações React (SPA).
    # Ela garante que se a pessoa acessar /callback direto, o NGINX 
    # não dê erro 404 e sim repasse para o index.html gerenciar a rota.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
